### ISSUE TITLE
Make the user guide for sharing more apparent

### ISSUE THREAD

**Issue by droumis** [awesome-panel/awesome-panel#78]
### Request

As it's not clear how to contribute without first reading the User Guide, the User Guide link effectively becomes a critical part of the call to action. My request is to add the User Guide link somewhere in the top left of the Sharing Page, and also on the Sharing Gallery page.

Additionally, I think that 'Sharing Gallery' might be better just named 'Gallery', and 'Sharing' as either 'Share' or 'Contribute' to make it more of a call to action.

### Motivation

People need to read the User Guide to figure it out, and currently, there is a lot to parse through (from left to right and waiting for the app to render) on the Sharing page before people get over to the small 'User Guide' link. 

![image](https://user-images.githubusercontent.com/6613202/203298106-6d2c6565-b2f9-41e5-8fda-519fa55d9f80.png)

### Alternatives

Make it more clear how to contribute to the gallery without having to send people out to the github user guide

**Comment by MarcSkovMadsen** [comment]
Thanks. Feedback makes a world of a difference.

**Comment by MarcSkovMadsen** [comment]
Regarding renaming the *Sharing Gallery*/ `sharing_gallery` to *Gallery*/`gallery`, I am a bit hesitant because those terms have been taken for the last two year by the normal awesome panel gallery of apps running on the server. So there would be thousand of links shared on social media, discourse etc that suddenly would not link to the correct gallery.

**Comment by MarcSkovMadsen** [comment]
Closed by https://github.com/awesome-panel/panel-sharing/pull/35#issue-1460498995

I hope you will take a look at it @droumis and let me know if you see more quick wins. Thanks.
